#!/usr/bin/env node

"use strict";

const util = require("util");
const readdir = util.promisify(require("fs").readdir);

const path = require("path");

const exec = util.promisify(require("child_process").exec);

(async () => {
    const files = (await readdir("test")).filter(name => path.extname(name) === ".js");
    
    for(const file of files) {
        await exec(`npx espower test/${ file } | npx exorcist docs/test/power.${ file }.map > docs/test/power.${ file }`);
    }
})();