#!/usr/bin/env node

"use strict";

const util = require("util");
const readdir = util.promisify(require("fs").readdir);

const path = require("path");

const exec = util.promisify(require("child_process").exec);

(async () => {
    const files = (await readdir("test")).filter(name => path.extname(name) === ".js");
    
    for(const file of files) {
        const base = path.basename(file, ".js");
        exec(`npx espower test/${ base }.js | npx exorcist docs/test/${ base }.power.js.map > docs/test/${ base }.power.js`);
    }
})();