#!/usr/bin/env node

"use strict";

const gray = "\x1b[90m";
const reset = "\x1b[0m";

const path = require("path");
const util = require("util");
const readdir = util.promisify(require("fs").readdir);
const exec = util.promisify(require("child_process").exec);

(async () => {
  const files = (await readdir("test")).filter((name) => {
    return path.extname(name) === ".js";
  });

  for (const file of files) {
    const base = path.basename(file, ".js");
    const command = `npx espower test/${ base }.js | npx exorcist -r ./ docs/test/${ base }.power.js.map > docs/test/${ base }.power.js`;

    console.log(`${gray}$ ${command}${reset}`);
    exec(command);
  }
})();
